eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/

server:
  port: 8766
  tomcat: #tomcat最大线程数
    max-threads: 50

spring:
  application:
    name: service-order-feign-degrade

feign:  #开启Hystrix
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillseconds: 3000
